---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crossplane-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for deploying Crossplane with ArgoCD
  sourceRepos:
  - ${GIT_REPOSITORY}

  destinations:
  - namespace: crossplane-system
    server: https://kubernetes.default.svc   
  - namespace: kube-system
    server: https://kubernetes.default.svc   
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc  

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding    
  - group: 'policy'
    kind: PodSecurityPolicy     
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'pkg.crossplane.io'
    kind: Configuration    
  - group: 'pkg.crossplane.io'
    kind: Lock   
  - group: 'pkg.crossplane.io'
    kind: Provider        
  - group: 'gcp.crossplane.io'
    kind: ProviderConfig     
  - group: 'iam.gcp.crossplane.io'
    kind: ServiceAccount